//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MalikP.BusinessJournal.Data.Service.JusticeServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://anasoft.com/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ObchodnyVestnikPodanie", Namespace="http://anasoft.com/")]
    [System.SerializableAttribute()]
    public partial class ObchodnyVestnikPodanie : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZnackaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SablonaKodField;
        
        private int SablonaVerziaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MalikP.BusinessJournal.Data.Service.JusticeServiceReference.ObchodnyVestnik ObchodnyVestnikField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FormularUdajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MalikP.BusinessJournal.Data.Service.JusticeServiceReference.ArrayOfString PrilohyReferencieField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Znacka {
            get {
                return this.ZnackaField;
            }
            set {
                if ((object.ReferenceEquals(this.ZnackaField, value) != true)) {
                    this.ZnackaField = value;
                    this.RaisePropertyChanged("Znacka");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string SablonaKod {
            get {
                return this.SablonaKodField;
            }
            set {
                if ((object.ReferenceEquals(this.SablonaKodField, value) != true)) {
                    this.SablonaKodField = value;
                    this.RaisePropertyChanged("SablonaKod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int SablonaVerzia {
            get {
                return this.SablonaVerziaField;
            }
            set {
                if ((this.SablonaVerziaField.Equals(value) != true)) {
                    this.SablonaVerziaField = value;
                    this.RaisePropertyChanged("SablonaVerzia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public MalikP.BusinessJournal.Data.Service.JusticeServiceReference.ObchodnyVestnik ObchodnyVestnik {
            get {
                return this.ObchodnyVestnikField;
            }
            set {
                if ((object.ReferenceEquals(this.ObchodnyVestnikField, value) != true)) {
                    this.ObchodnyVestnikField = value;
                    this.RaisePropertyChanged("ObchodnyVestnik");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string FormularUdaje {
            get {
                return this.FormularUdajeField;
            }
            set {
                if ((object.ReferenceEquals(this.FormularUdajeField, value) != true)) {
                    this.FormularUdajeField = value;
                    this.RaisePropertyChanged("FormularUdaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public MalikP.BusinessJournal.Data.Service.JusticeServiceReference.ArrayOfString PrilohyReferencie {
            get {
                return this.PrilohyReferencieField;
            }
            set {
                if ((object.ReferenceEquals(this.PrilohyReferencieField, value) != true)) {
                    this.PrilohyReferencieField = value;
                    this.RaisePropertyChanged("PrilohyReferencie");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ObchodnyVestnik", Namespace="http://anasoft.com/")]
    [System.SerializableAttribute()]
    public partial class ObchodnyVestnik : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int CisloField;
        
        private int RocnikField;
        
        private System.DateTime DenVydaniaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Cislo {
            get {
                return this.CisloField;
            }
            set {
                if ((this.CisloField.Equals(value) != true)) {
                    this.CisloField = value;
                    this.RaisePropertyChanged("Cislo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Rocnik {
            get {
                return this.RocnikField;
            }
            set {
                if ((this.RocnikField.Equals(value) != true)) {
                    this.RocnikField = value;
                    this.RaisePropertyChanged("Rocnik");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.DateTime DenVydania {
            get {
                return this.DenVydaniaField;
            }
            set {
                if ((this.DenVydaniaField.Equals(value) != true)) {
                    this.DenVydaniaField = value;
                    this.RaisePropertyChanged("DenVydania");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ObchodnyVestnikKapitola", Namespace="http://anasoft.com/")]
    [System.SerializableAttribute()]
    public partial class ObchodnyVestnikKapitola : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NazovField;
        
        private MalikP.BusinessJournal.Data.Service.JusticeServiceReference.SuborStav StavField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nazov {
            get {
                return this.NazovField;
            }
            set {
                if ((object.ReferenceEquals(this.NazovField, value) != true)) {
                    this.NazovField = value;
                    this.RaisePropertyChanged("Nazov");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public MalikP.BusinessJournal.Data.Service.JusticeServiceReference.SuborStav Stav {
            get {
                return this.StavField;
            }
            set {
                if ((this.StavField.Equals(value) != true)) {
                    this.StavField = value;
                    this.RaisePropertyChanged("Stav");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SuborStav", Namespace="http://anasoft.com/")]
    public enum SuborStav : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Zmeneny = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Nezmeneny = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Neznamy = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://anasoft.com/", ConfigurationName="JusticeServiceReference.PodanieExportSoap")]
    public interface PodanieExportSoap {
        
        // CODEGEN: Generating message contract since element name login from namespace http://anasoft.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://anasoft.com/StiahnutPodaniaOV", ReplyAction="*")]
        MalikP.BusinessJournal.Data.Service.JusticeServiceReference.StiahnutPodaniaOVResponse StiahnutPodaniaOV(MalikP.BusinessJournal.Data.Service.JusticeServiceReference.StiahnutPodaniaOVRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://anasoft.com/StiahnutPodaniaOV", ReplyAction="*")]
        System.IAsyncResult BeginStiahnutPodaniaOV(MalikP.BusinessJournal.Data.Service.JusticeServiceReference.StiahnutPodaniaOVRequest request, System.AsyncCallback callback, object asyncState);
        
        MalikP.BusinessJournal.Data.Service.JusticeServiceReference.StiahnutPodaniaOVResponse EndStiahnutPodaniaOV(System.IAsyncResult result);
        
        // CODEGEN: Generating message contract since element name login from namespace http://anasoft.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://anasoft.com/StiahnutPodaniaOVPodlaTypu", ReplyAction="*")]
        MalikP.BusinessJournal.Data.Service.JusticeServiceReference.StiahnutPodaniaOVPodlaTypuResponse StiahnutPodaniaOVPodlaTypu(MalikP.BusinessJournal.Data.Service.JusticeServiceReference.StiahnutPodaniaOVPodlaTypuRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://anasoft.com/StiahnutPodaniaOVPodlaTypu", ReplyAction="*")]
        System.IAsyncResult BeginStiahnutPodaniaOVPodlaTypu(MalikP.BusinessJournal.Data.Service.JusticeServiceReference.StiahnutPodaniaOVPodlaTypuRequest request, System.AsyncCallback callback, object asyncState);
        
        MalikP.BusinessJournal.Data.Service.JusticeServiceReference.StiahnutPodaniaOVPodlaTypuResponse EndStiahnutPodaniaOVPodlaTypu(System.IAsyncResult result);
        
        // CODEGEN: Generating message contract since element name login from namespace http://anasoft.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://anasoft.com/ZiskatZoznamVydanychOV", ReplyAction="*")]
        MalikP.BusinessJournal.Data.Service.JusticeServiceReference.ZiskatZoznamVydanychOVResponse ZiskatZoznamVydanychOV(MalikP.BusinessJournal.Data.Service.JusticeServiceReference.ZiskatZoznamVydanychOVRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://anasoft.com/ZiskatZoznamVydanychOV", ReplyAction="*")]
        System.IAsyncResult BeginZiskatZoznamVydanychOV(MalikP.BusinessJournal.Data.Service.JusticeServiceReference.ZiskatZoznamVydanychOVRequest request, System.AsyncCallback callback, object asyncState);
        
        MalikP.BusinessJournal.Data.Service.JusticeServiceReference.ZiskatZoznamVydanychOVResponse EndZiskatZoznamVydanychOV(System.IAsyncResult result);
        
        // CODEGEN: Generating message contract since element name login from namespace http://anasoft.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://anasoft.com/ZiskatPoslednyVydanyOV", ReplyAction="*")]
        MalikP.BusinessJournal.Data.Service.JusticeServiceReference.ZiskatPoslednyVydanyOVResponse ZiskatPoslednyVydanyOV(MalikP.BusinessJournal.Data.Service.JusticeServiceReference.ZiskatPoslednyVydanyOVRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://anasoft.com/ZiskatPoslednyVydanyOV", ReplyAction="*")]
        System.IAsyncResult BeginZiskatPoslednyVydanyOV(MalikP.BusinessJournal.Data.Service.JusticeServiceReference.ZiskatPoslednyVydanyOVRequest request, System.AsyncCallback callback, object asyncState);
        
        MalikP.BusinessJournal.Data.Service.JusticeServiceReference.ZiskatPoslednyVydanyOVResponse EndZiskatPoslednyVydanyOV(System.IAsyncResult result);
        
        // CODEGEN: Generating message contract since element name login from namespace http://anasoft.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://anasoft.com/SkontrolovatZmenyOV", ReplyAction="*")]
        MalikP.BusinessJournal.Data.Service.JusticeServiceReference.SkontrolovatZmenyOVResponse SkontrolovatZmenyOV(MalikP.BusinessJournal.Data.Service.JusticeServiceReference.SkontrolovatZmenyOVRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://anasoft.com/SkontrolovatZmenyOV", ReplyAction="*")]
        System.IAsyncResult BeginSkontrolovatZmenyOV(MalikP.BusinessJournal.Data.Service.JusticeServiceReference.SkontrolovatZmenyOVRequest request, System.AsyncCallback callback, object asyncState);
        
        MalikP.BusinessJournal.Data.Service.JusticeServiceReference.SkontrolovatZmenyOVResponse EndSkontrolovatZmenyOV(System.IAsyncResult result);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StiahnutPodaniaOVRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="StiahnutPodaniaOV", Namespace="http://anasoft.com/", Order=0)]
        public MalikP.BusinessJournal.Data.Service.JusticeServiceReference.StiahnutPodaniaOVRequestBody Body;
        
        public StiahnutPodaniaOVRequest() {
        }
        
        public StiahnutPodaniaOVRequest(MalikP.BusinessJournal.Data.Service.JusticeServiceReference.StiahnutPodaniaOVRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://anasoft.com/")]
    public partial class StiahnutPodaniaOVRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string login;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int cislo;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int rocnik;
        
        public StiahnutPodaniaOVRequestBody() {
        }
        
        public StiahnutPodaniaOVRequestBody(string login, string password, int cislo, int rocnik) {
            this.login = login;
            this.password = password;
            this.cislo = cislo;
            this.rocnik = rocnik;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StiahnutPodaniaOVResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="StiahnutPodaniaOVResponse", Namespace="http://anasoft.com/", Order=0)]
        public MalikP.BusinessJournal.Data.Service.JusticeServiceReference.StiahnutPodaniaOVResponseBody Body;
        
        public StiahnutPodaniaOVResponse() {
        }
        
        public StiahnutPodaniaOVResponse(MalikP.BusinessJournal.Data.Service.JusticeServiceReference.StiahnutPodaniaOVResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://anasoft.com/")]
    public partial class StiahnutPodaniaOVResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string StiahnutPodaniaOVResult;
        
        public StiahnutPodaniaOVResponseBody() {
        }
        
        public StiahnutPodaniaOVResponseBody(string StiahnutPodaniaOVResult) {
            this.StiahnutPodaniaOVResult = StiahnutPodaniaOVResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StiahnutPodaniaOVPodlaTypuRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="StiahnutPodaniaOVPodlaTypu", Namespace="http://anasoft.com/", Order=0)]
        public MalikP.BusinessJournal.Data.Service.JusticeServiceReference.StiahnutPodaniaOVPodlaTypuRequestBody Body;
        
        public StiahnutPodaniaOVPodlaTypuRequest() {
        }
        
        public StiahnutPodaniaOVPodlaTypuRequest(MalikP.BusinessJournal.Data.Service.JusticeServiceReference.StiahnutPodaniaOVPodlaTypuRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://anasoft.com/")]
    public partial class StiahnutPodaniaOVPodlaTypuRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string login;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public MalikP.BusinessJournal.Data.Service.JusticeServiceReference.ArrayOfString sablonaKod;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.DateTime datumZverejneniaOd;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.DateTime datumZverejneniaDo;
        
        public StiahnutPodaniaOVPodlaTypuRequestBody() {
        }
        
        public StiahnutPodaniaOVPodlaTypuRequestBody(string login, string password, MalikP.BusinessJournal.Data.Service.JusticeServiceReference.ArrayOfString sablonaKod, System.DateTime datumZverejneniaOd, System.DateTime datumZverejneniaDo) {
            this.login = login;
            this.password = password;
            this.sablonaKod = sablonaKod;
            this.datumZverejneniaOd = datumZverejneniaOd;
            this.datumZverejneniaDo = datumZverejneniaDo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StiahnutPodaniaOVPodlaTypuResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="StiahnutPodaniaOVPodlaTypuResponse", Namespace="http://anasoft.com/", Order=0)]
        public MalikP.BusinessJournal.Data.Service.JusticeServiceReference.StiahnutPodaniaOVPodlaTypuResponseBody Body;
        
        public StiahnutPodaniaOVPodlaTypuResponse() {
        }
        
        public StiahnutPodaniaOVPodlaTypuResponse(MalikP.BusinessJournal.Data.Service.JusticeServiceReference.StiahnutPodaniaOVPodlaTypuResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://anasoft.com/")]
    public partial class StiahnutPodaniaOVPodlaTypuResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MalikP.BusinessJournal.Data.Service.JusticeServiceReference.ObchodnyVestnikPodanie[] StiahnutPodaniaOVPodlaTypuResult;
        
        public StiahnutPodaniaOVPodlaTypuResponseBody() {
        }
        
        public StiahnutPodaniaOVPodlaTypuResponseBody(MalikP.BusinessJournal.Data.Service.JusticeServiceReference.ObchodnyVestnikPodanie[] StiahnutPodaniaOVPodlaTypuResult) {
            this.StiahnutPodaniaOVPodlaTypuResult = StiahnutPodaniaOVPodlaTypuResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZiskatZoznamVydanychOVRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ZiskatZoznamVydanychOV", Namespace="http://anasoft.com/", Order=0)]
        public MalikP.BusinessJournal.Data.Service.JusticeServiceReference.ZiskatZoznamVydanychOVRequestBody Body;
        
        public ZiskatZoznamVydanychOVRequest() {
        }
        
        public ZiskatZoznamVydanychOVRequest(MalikP.BusinessJournal.Data.Service.JusticeServiceReference.ZiskatZoznamVydanychOVRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://anasoft.com/")]
    public partial class ZiskatZoznamVydanychOVRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string login;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public ZiskatZoznamVydanychOVRequestBody() {
        }
        
        public ZiskatZoznamVydanychOVRequestBody(string login, string password) {
            this.login = login;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZiskatZoznamVydanychOVResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ZiskatZoznamVydanychOVResponse", Namespace="http://anasoft.com/", Order=0)]
        public MalikP.BusinessJournal.Data.Service.JusticeServiceReference.ZiskatZoznamVydanychOVResponseBody Body;
        
        public ZiskatZoznamVydanychOVResponse() {
        }
        
        public ZiskatZoznamVydanychOVResponse(MalikP.BusinessJournal.Data.Service.JusticeServiceReference.ZiskatZoznamVydanychOVResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://anasoft.com/")]
    public partial class ZiskatZoznamVydanychOVResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MalikP.BusinessJournal.Data.Service.JusticeServiceReference.ObchodnyVestnik[] ZiskatZoznamVydanychOVResult;
        
        public ZiskatZoznamVydanychOVResponseBody() {
        }
        
        public ZiskatZoznamVydanychOVResponseBody(MalikP.BusinessJournal.Data.Service.JusticeServiceReference.ObchodnyVestnik[] ZiskatZoznamVydanychOVResult) {
            this.ZiskatZoznamVydanychOVResult = ZiskatZoznamVydanychOVResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZiskatPoslednyVydanyOVRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ZiskatPoslednyVydanyOV", Namespace="http://anasoft.com/", Order=0)]
        public MalikP.BusinessJournal.Data.Service.JusticeServiceReference.ZiskatPoslednyVydanyOVRequestBody Body;
        
        public ZiskatPoslednyVydanyOVRequest() {
        }
        
        public ZiskatPoslednyVydanyOVRequest(MalikP.BusinessJournal.Data.Service.JusticeServiceReference.ZiskatPoslednyVydanyOVRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://anasoft.com/")]
    public partial class ZiskatPoslednyVydanyOVRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string login;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public ZiskatPoslednyVydanyOVRequestBody() {
        }
        
        public ZiskatPoslednyVydanyOVRequestBody(string login, string password) {
            this.login = login;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZiskatPoslednyVydanyOVResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ZiskatPoslednyVydanyOVResponse", Namespace="http://anasoft.com/", Order=0)]
        public MalikP.BusinessJournal.Data.Service.JusticeServiceReference.ZiskatPoslednyVydanyOVResponseBody Body;
        
        public ZiskatPoslednyVydanyOVResponse() {
        }
        
        public ZiskatPoslednyVydanyOVResponse(MalikP.BusinessJournal.Data.Service.JusticeServiceReference.ZiskatPoslednyVydanyOVResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://anasoft.com/")]
    public partial class ZiskatPoslednyVydanyOVResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MalikP.BusinessJournal.Data.Service.JusticeServiceReference.ObchodnyVestnik ZiskatPoslednyVydanyOVResult;
        
        public ZiskatPoslednyVydanyOVResponseBody() {
        }
        
        public ZiskatPoslednyVydanyOVResponseBody(MalikP.BusinessJournal.Data.Service.JusticeServiceReference.ObchodnyVestnik ZiskatPoslednyVydanyOVResult) {
            this.ZiskatPoslednyVydanyOVResult = ZiskatPoslednyVydanyOVResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SkontrolovatZmenyOVRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SkontrolovatZmenyOV", Namespace="http://anasoft.com/", Order=0)]
        public MalikP.BusinessJournal.Data.Service.JusticeServiceReference.SkontrolovatZmenyOVRequestBody Body;
        
        public SkontrolovatZmenyOVRequest() {
        }
        
        public SkontrolovatZmenyOVRequest(MalikP.BusinessJournal.Data.Service.JusticeServiceReference.SkontrolovatZmenyOVRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://anasoft.com/")]
    public partial class SkontrolovatZmenyOVRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string login;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int cislo;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int rocnik;
        
        public SkontrolovatZmenyOVRequestBody() {
        }
        
        public SkontrolovatZmenyOVRequestBody(string login, string password, int cislo, int rocnik) {
            this.login = login;
            this.password = password;
            this.cislo = cislo;
            this.rocnik = rocnik;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SkontrolovatZmenyOVResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SkontrolovatZmenyOVResponse", Namespace="http://anasoft.com/", Order=0)]
        public MalikP.BusinessJournal.Data.Service.JusticeServiceReference.SkontrolovatZmenyOVResponseBody Body;
        
        public SkontrolovatZmenyOVResponse() {
        }
        
        public SkontrolovatZmenyOVResponse(MalikP.BusinessJournal.Data.Service.JusticeServiceReference.SkontrolovatZmenyOVResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://anasoft.com/")]
    public partial class SkontrolovatZmenyOVResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MalikP.BusinessJournal.Data.Service.JusticeServiceReference.ObchodnyVestnikKapitola[] SkontrolovatZmenyOVResult;
        
        public SkontrolovatZmenyOVResponseBody() {
        }
        
        public SkontrolovatZmenyOVResponseBody(MalikP.BusinessJournal.Data.Service.JusticeServiceReference.ObchodnyVestnikKapitola[] SkontrolovatZmenyOVResult) {
            this.SkontrolovatZmenyOVResult = SkontrolovatZmenyOVResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PodanieExportSoapChannel : MalikP.BusinessJournal.Data.Service.JusticeServiceReference.PodanieExportSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StiahnutPodaniaOVCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public StiahnutPodaniaOVCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StiahnutPodaniaOVPodlaTypuCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public StiahnutPodaniaOVPodlaTypuCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public MalikP.BusinessJournal.Data.Service.JusticeServiceReference.ObchodnyVestnikPodanie[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((MalikP.BusinessJournal.Data.Service.JusticeServiceReference.ObchodnyVestnikPodanie[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ZiskatZoznamVydanychOVCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ZiskatZoznamVydanychOVCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public MalikP.BusinessJournal.Data.Service.JusticeServiceReference.ObchodnyVestnik[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((MalikP.BusinessJournal.Data.Service.JusticeServiceReference.ObchodnyVestnik[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ZiskatPoslednyVydanyOVCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ZiskatPoslednyVydanyOVCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public MalikP.BusinessJournal.Data.Service.JusticeServiceReference.ObchodnyVestnik Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((MalikP.BusinessJournal.Data.Service.JusticeServiceReference.ObchodnyVestnik)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SkontrolovatZmenyOVCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public SkontrolovatZmenyOVCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public MalikP.BusinessJournal.Data.Service.JusticeServiceReference.ObchodnyVestnikKapitola[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((MalikP.BusinessJournal.Data.Service.JusticeServiceReference.ObchodnyVestnikKapitola[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PodanieExportSoapClient : System.ServiceModel.ClientBase<MalikP.BusinessJournal.Data.Service.JusticeServiceReference.PodanieExportSoap>, MalikP.BusinessJournal.Data.Service.JusticeServiceReference.PodanieExportSoap {
        
        private BeginOperationDelegate onBeginStiahnutPodaniaOVDelegate;
        
        private EndOperationDelegate onEndStiahnutPodaniaOVDelegate;
        
        private System.Threading.SendOrPostCallback onStiahnutPodaniaOVCompletedDelegate;
        
        private BeginOperationDelegate onBeginStiahnutPodaniaOVPodlaTypuDelegate;
        
        private EndOperationDelegate onEndStiahnutPodaniaOVPodlaTypuDelegate;
        
        private System.Threading.SendOrPostCallback onStiahnutPodaniaOVPodlaTypuCompletedDelegate;
        
        private BeginOperationDelegate onBeginZiskatZoznamVydanychOVDelegate;
        
        private EndOperationDelegate onEndZiskatZoznamVydanychOVDelegate;
        
        private System.Threading.SendOrPostCallback onZiskatZoznamVydanychOVCompletedDelegate;
        
        private BeginOperationDelegate onBeginZiskatPoslednyVydanyOVDelegate;
        
        private EndOperationDelegate onEndZiskatPoslednyVydanyOVDelegate;
        
        private System.Threading.SendOrPostCallback onZiskatPoslednyVydanyOVCompletedDelegate;
        
        private BeginOperationDelegate onBeginSkontrolovatZmenyOVDelegate;
        
        private EndOperationDelegate onEndSkontrolovatZmenyOVDelegate;
        
        private System.Threading.SendOrPostCallback onSkontrolovatZmenyOVCompletedDelegate;
        
        public PodanieExportSoapClient() {
        }
        
        public PodanieExportSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PodanieExportSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PodanieExportSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PodanieExportSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<StiahnutPodaniaOVCompletedEventArgs> StiahnutPodaniaOVCompleted;
        
        public event System.EventHandler<StiahnutPodaniaOVPodlaTypuCompletedEventArgs> StiahnutPodaniaOVPodlaTypuCompleted;
        
        public event System.EventHandler<ZiskatZoznamVydanychOVCompletedEventArgs> ZiskatZoznamVydanychOVCompleted;
        
        public event System.EventHandler<ZiskatPoslednyVydanyOVCompletedEventArgs> ZiskatPoslednyVydanyOVCompleted;
        
        public event System.EventHandler<SkontrolovatZmenyOVCompletedEventArgs> SkontrolovatZmenyOVCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MalikP.BusinessJournal.Data.Service.JusticeServiceReference.StiahnutPodaniaOVResponse MalikP.BusinessJournal.Data.Service.JusticeServiceReference.PodanieExportSoap.StiahnutPodaniaOV(MalikP.BusinessJournal.Data.Service.JusticeServiceReference.StiahnutPodaniaOVRequest request) {
            return base.Channel.StiahnutPodaniaOV(request);
        }
        
        public string StiahnutPodaniaOV(string login, string password, int cislo, int rocnik) {
            MalikP.BusinessJournal.Data.Service.JusticeServiceReference.StiahnutPodaniaOVRequest inValue = new MalikP.BusinessJournal.Data.Service.JusticeServiceReference.StiahnutPodaniaOVRequest();
            inValue.Body = new MalikP.BusinessJournal.Data.Service.JusticeServiceReference.StiahnutPodaniaOVRequestBody();
            inValue.Body.login = login;
            inValue.Body.password = password;
            inValue.Body.cislo = cislo;
            inValue.Body.rocnik = rocnik;
            MalikP.BusinessJournal.Data.Service.JusticeServiceReference.StiahnutPodaniaOVResponse retVal = ((MalikP.BusinessJournal.Data.Service.JusticeServiceReference.PodanieExportSoap)(this)).StiahnutPodaniaOV(inValue);
            return retVal.Body.StiahnutPodaniaOVResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult MalikP.BusinessJournal.Data.Service.JusticeServiceReference.PodanieExportSoap.BeginStiahnutPodaniaOV(MalikP.BusinessJournal.Data.Service.JusticeServiceReference.StiahnutPodaniaOVRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginStiahnutPodaniaOV(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginStiahnutPodaniaOV(string login, string password, int cislo, int rocnik, System.AsyncCallback callback, object asyncState) {
            MalikP.BusinessJournal.Data.Service.JusticeServiceReference.StiahnutPodaniaOVRequest inValue = new MalikP.BusinessJournal.Data.Service.JusticeServiceReference.StiahnutPodaniaOVRequest();
            inValue.Body = new MalikP.BusinessJournal.Data.Service.JusticeServiceReference.StiahnutPodaniaOVRequestBody();
            inValue.Body.login = login;
            inValue.Body.password = password;
            inValue.Body.cislo = cislo;
            inValue.Body.rocnik = rocnik;
            return ((MalikP.BusinessJournal.Data.Service.JusticeServiceReference.PodanieExportSoap)(this)).BeginStiahnutPodaniaOV(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MalikP.BusinessJournal.Data.Service.JusticeServiceReference.StiahnutPodaniaOVResponse MalikP.BusinessJournal.Data.Service.JusticeServiceReference.PodanieExportSoap.EndStiahnutPodaniaOV(System.IAsyncResult result) {
            return base.Channel.EndStiahnutPodaniaOV(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public string EndStiahnutPodaniaOV(System.IAsyncResult result) {
            MalikP.BusinessJournal.Data.Service.JusticeServiceReference.StiahnutPodaniaOVResponse retVal = ((MalikP.BusinessJournal.Data.Service.JusticeServiceReference.PodanieExportSoap)(this)).EndStiahnutPodaniaOV(result);
            return retVal.Body.StiahnutPodaniaOVResult;
        }
        
        private System.IAsyncResult OnBeginStiahnutPodaniaOV(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string login = ((string)(inValues[0]));
            string password = ((string)(inValues[1]));
            int cislo = ((int)(inValues[2]));
            int rocnik = ((int)(inValues[3]));
            return this.BeginStiahnutPodaniaOV(login, password, cislo, rocnik, callback, asyncState);
        }
        
        private object[] OnEndStiahnutPodaniaOV(System.IAsyncResult result) {
            string retVal = this.EndStiahnutPodaniaOV(result);
            return new object[] {
                    retVal};
        }
        
        private void OnStiahnutPodaniaOVCompleted(object state) {
            if ((this.StiahnutPodaniaOVCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.StiahnutPodaniaOVCompleted(this, new StiahnutPodaniaOVCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void StiahnutPodaniaOVAsync(string login, string password, int cislo, int rocnik) {
            this.StiahnutPodaniaOVAsync(login, password, cislo, rocnik, null);
        }
        
        public void StiahnutPodaniaOVAsync(string login, string password, int cislo, int rocnik, object userState) {
            if ((this.onBeginStiahnutPodaniaOVDelegate == null)) {
                this.onBeginStiahnutPodaniaOVDelegate = new BeginOperationDelegate(this.OnBeginStiahnutPodaniaOV);
            }
            if ((this.onEndStiahnutPodaniaOVDelegate == null)) {
                this.onEndStiahnutPodaniaOVDelegate = new EndOperationDelegate(this.OnEndStiahnutPodaniaOV);
            }
            if ((this.onStiahnutPodaniaOVCompletedDelegate == null)) {
                this.onStiahnutPodaniaOVCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnStiahnutPodaniaOVCompleted);
            }
            base.InvokeAsync(this.onBeginStiahnutPodaniaOVDelegate, new object[] {
                        login,
                        password,
                        cislo,
                        rocnik}, this.onEndStiahnutPodaniaOVDelegate, this.onStiahnutPodaniaOVCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MalikP.BusinessJournal.Data.Service.JusticeServiceReference.StiahnutPodaniaOVPodlaTypuResponse MalikP.BusinessJournal.Data.Service.JusticeServiceReference.PodanieExportSoap.StiahnutPodaniaOVPodlaTypu(MalikP.BusinessJournal.Data.Service.JusticeServiceReference.StiahnutPodaniaOVPodlaTypuRequest request) {
            return base.Channel.StiahnutPodaniaOVPodlaTypu(request);
        }
        
        public MalikP.BusinessJournal.Data.Service.JusticeServiceReference.ObchodnyVestnikPodanie[] StiahnutPodaniaOVPodlaTypu(string login, string password, MalikP.BusinessJournal.Data.Service.JusticeServiceReference.ArrayOfString sablonaKod, System.DateTime datumZverejneniaOd, System.DateTime datumZverejneniaDo) {
            MalikP.BusinessJournal.Data.Service.JusticeServiceReference.StiahnutPodaniaOVPodlaTypuRequest inValue = new MalikP.BusinessJournal.Data.Service.JusticeServiceReference.StiahnutPodaniaOVPodlaTypuRequest();
            inValue.Body = new MalikP.BusinessJournal.Data.Service.JusticeServiceReference.StiahnutPodaniaOVPodlaTypuRequestBody();
            inValue.Body.login = login;
            inValue.Body.password = password;
            inValue.Body.sablonaKod = sablonaKod;
            inValue.Body.datumZverejneniaOd = datumZverejneniaOd;
            inValue.Body.datumZverejneniaDo = datumZverejneniaDo;
            MalikP.BusinessJournal.Data.Service.JusticeServiceReference.StiahnutPodaniaOVPodlaTypuResponse retVal = ((MalikP.BusinessJournal.Data.Service.JusticeServiceReference.PodanieExportSoap)(this)).StiahnutPodaniaOVPodlaTypu(inValue);
            return retVal.Body.StiahnutPodaniaOVPodlaTypuResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult MalikP.BusinessJournal.Data.Service.JusticeServiceReference.PodanieExportSoap.BeginStiahnutPodaniaOVPodlaTypu(MalikP.BusinessJournal.Data.Service.JusticeServiceReference.StiahnutPodaniaOVPodlaTypuRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginStiahnutPodaniaOVPodlaTypu(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginStiahnutPodaniaOVPodlaTypu(string login, string password, MalikP.BusinessJournal.Data.Service.JusticeServiceReference.ArrayOfString sablonaKod, System.DateTime datumZverejneniaOd, System.DateTime datumZverejneniaDo, System.AsyncCallback callback, object asyncState) {
            MalikP.BusinessJournal.Data.Service.JusticeServiceReference.StiahnutPodaniaOVPodlaTypuRequest inValue = new MalikP.BusinessJournal.Data.Service.JusticeServiceReference.StiahnutPodaniaOVPodlaTypuRequest();
            inValue.Body = new MalikP.BusinessJournal.Data.Service.JusticeServiceReference.StiahnutPodaniaOVPodlaTypuRequestBody();
            inValue.Body.login = login;
            inValue.Body.password = password;
            inValue.Body.sablonaKod = sablonaKod;
            inValue.Body.datumZverejneniaOd = datumZverejneniaOd;
            inValue.Body.datumZverejneniaDo = datumZverejneniaDo;
            return ((MalikP.BusinessJournal.Data.Service.JusticeServiceReference.PodanieExportSoap)(this)).BeginStiahnutPodaniaOVPodlaTypu(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MalikP.BusinessJournal.Data.Service.JusticeServiceReference.StiahnutPodaniaOVPodlaTypuResponse MalikP.BusinessJournal.Data.Service.JusticeServiceReference.PodanieExportSoap.EndStiahnutPodaniaOVPodlaTypu(System.IAsyncResult result) {
            return base.Channel.EndStiahnutPodaniaOVPodlaTypu(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public MalikP.BusinessJournal.Data.Service.JusticeServiceReference.ObchodnyVestnikPodanie[] EndStiahnutPodaniaOVPodlaTypu(System.IAsyncResult result) {
            MalikP.BusinessJournal.Data.Service.JusticeServiceReference.StiahnutPodaniaOVPodlaTypuResponse retVal = ((MalikP.BusinessJournal.Data.Service.JusticeServiceReference.PodanieExportSoap)(this)).EndStiahnutPodaniaOVPodlaTypu(result);
            return retVal.Body.StiahnutPodaniaOVPodlaTypuResult;
        }
        
        private System.IAsyncResult OnBeginStiahnutPodaniaOVPodlaTypu(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string login = ((string)(inValues[0]));
            string password = ((string)(inValues[1]));
            MalikP.BusinessJournal.Data.Service.JusticeServiceReference.ArrayOfString sablonaKod = ((MalikP.BusinessJournal.Data.Service.JusticeServiceReference.ArrayOfString)(inValues[2]));
            System.DateTime datumZverejneniaOd = ((System.DateTime)(inValues[3]));
            System.DateTime datumZverejneniaDo = ((System.DateTime)(inValues[4]));
            return this.BeginStiahnutPodaniaOVPodlaTypu(login, password, sablonaKod, datumZverejneniaOd, datumZverejneniaDo, callback, asyncState);
        }
        
        private object[] OnEndStiahnutPodaniaOVPodlaTypu(System.IAsyncResult result) {
            MalikP.BusinessJournal.Data.Service.JusticeServiceReference.ObchodnyVestnikPodanie[] retVal = this.EndStiahnutPodaniaOVPodlaTypu(result);
            return new object[] {
                    retVal};
        }
        
        private void OnStiahnutPodaniaOVPodlaTypuCompleted(object state) {
            if ((this.StiahnutPodaniaOVPodlaTypuCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.StiahnutPodaniaOVPodlaTypuCompleted(this, new StiahnutPodaniaOVPodlaTypuCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void StiahnutPodaniaOVPodlaTypuAsync(string login, string password, MalikP.BusinessJournal.Data.Service.JusticeServiceReference.ArrayOfString sablonaKod, System.DateTime datumZverejneniaOd, System.DateTime datumZverejneniaDo) {
            this.StiahnutPodaniaOVPodlaTypuAsync(login, password, sablonaKod, datumZverejneniaOd, datumZverejneniaDo, null);
        }
        
        public void StiahnutPodaniaOVPodlaTypuAsync(string login, string password, MalikP.BusinessJournal.Data.Service.JusticeServiceReference.ArrayOfString sablonaKod, System.DateTime datumZverejneniaOd, System.DateTime datumZverejneniaDo, object userState) {
            if ((this.onBeginStiahnutPodaniaOVPodlaTypuDelegate == null)) {
                this.onBeginStiahnutPodaniaOVPodlaTypuDelegate = new BeginOperationDelegate(this.OnBeginStiahnutPodaniaOVPodlaTypu);
            }
            if ((this.onEndStiahnutPodaniaOVPodlaTypuDelegate == null)) {
                this.onEndStiahnutPodaniaOVPodlaTypuDelegate = new EndOperationDelegate(this.OnEndStiahnutPodaniaOVPodlaTypu);
            }
            if ((this.onStiahnutPodaniaOVPodlaTypuCompletedDelegate == null)) {
                this.onStiahnutPodaniaOVPodlaTypuCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnStiahnutPodaniaOVPodlaTypuCompleted);
            }
            base.InvokeAsync(this.onBeginStiahnutPodaniaOVPodlaTypuDelegate, new object[] {
                        login,
                        password,
                        sablonaKod,
                        datumZverejneniaOd,
                        datumZverejneniaDo}, this.onEndStiahnutPodaniaOVPodlaTypuDelegate, this.onStiahnutPodaniaOVPodlaTypuCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MalikP.BusinessJournal.Data.Service.JusticeServiceReference.ZiskatZoznamVydanychOVResponse MalikP.BusinessJournal.Data.Service.JusticeServiceReference.PodanieExportSoap.ZiskatZoznamVydanychOV(MalikP.BusinessJournal.Data.Service.JusticeServiceReference.ZiskatZoznamVydanychOVRequest request) {
            return base.Channel.ZiskatZoznamVydanychOV(request);
        }
        
        public MalikP.BusinessJournal.Data.Service.JusticeServiceReference.ObchodnyVestnik[] ZiskatZoznamVydanychOV(string login, string password) {
            MalikP.BusinessJournal.Data.Service.JusticeServiceReference.ZiskatZoznamVydanychOVRequest inValue = new MalikP.BusinessJournal.Data.Service.JusticeServiceReference.ZiskatZoznamVydanychOVRequest();
            inValue.Body = new MalikP.BusinessJournal.Data.Service.JusticeServiceReference.ZiskatZoznamVydanychOVRequestBody();
            inValue.Body.login = login;
            inValue.Body.password = password;
            MalikP.BusinessJournal.Data.Service.JusticeServiceReference.ZiskatZoznamVydanychOVResponse retVal = ((MalikP.BusinessJournal.Data.Service.JusticeServiceReference.PodanieExportSoap)(this)).ZiskatZoznamVydanychOV(inValue);
            return retVal.Body.ZiskatZoznamVydanychOVResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult MalikP.BusinessJournal.Data.Service.JusticeServiceReference.PodanieExportSoap.BeginZiskatZoznamVydanychOV(MalikP.BusinessJournal.Data.Service.JusticeServiceReference.ZiskatZoznamVydanychOVRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginZiskatZoznamVydanychOV(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginZiskatZoznamVydanychOV(string login, string password, System.AsyncCallback callback, object asyncState) {
            MalikP.BusinessJournal.Data.Service.JusticeServiceReference.ZiskatZoznamVydanychOVRequest inValue = new MalikP.BusinessJournal.Data.Service.JusticeServiceReference.ZiskatZoznamVydanychOVRequest();
            inValue.Body = new MalikP.BusinessJournal.Data.Service.JusticeServiceReference.ZiskatZoznamVydanychOVRequestBody();
            inValue.Body.login = login;
            inValue.Body.password = password;
            return ((MalikP.BusinessJournal.Data.Service.JusticeServiceReference.PodanieExportSoap)(this)).BeginZiskatZoznamVydanychOV(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MalikP.BusinessJournal.Data.Service.JusticeServiceReference.ZiskatZoznamVydanychOVResponse MalikP.BusinessJournal.Data.Service.JusticeServiceReference.PodanieExportSoap.EndZiskatZoznamVydanychOV(System.IAsyncResult result) {
            return base.Channel.EndZiskatZoznamVydanychOV(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public MalikP.BusinessJournal.Data.Service.JusticeServiceReference.ObchodnyVestnik[] EndZiskatZoznamVydanychOV(System.IAsyncResult result) {
            MalikP.BusinessJournal.Data.Service.JusticeServiceReference.ZiskatZoznamVydanychOVResponse retVal = ((MalikP.BusinessJournal.Data.Service.JusticeServiceReference.PodanieExportSoap)(this)).EndZiskatZoznamVydanychOV(result);
            return retVal.Body.ZiskatZoznamVydanychOVResult;
        }
        
        private System.IAsyncResult OnBeginZiskatZoznamVydanychOV(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string login = ((string)(inValues[0]));
            string password = ((string)(inValues[1]));
            return this.BeginZiskatZoznamVydanychOV(login, password, callback, asyncState);
        }
        
        private object[] OnEndZiskatZoznamVydanychOV(System.IAsyncResult result) {
            MalikP.BusinessJournal.Data.Service.JusticeServiceReference.ObchodnyVestnik[] retVal = this.EndZiskatZoznamVydanychOV(result);
            return new object[] {
                    retVal};
        }
        
        private void OnZiskatZoznamVydanychOVCompleted(object state) {
            if ((this.ZiskatZoznamVydanychOVCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ZiskatZoznamVydanychOVCompleted(this, new ZiskatZoznamVydanychOVCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ZiskatZoznamVydanychOVAsync(string login, string password) {
            this.ZiskatZoznamVydanychOVAsync(login, password, null);
        }
        
        public void ZiskatZoznamVydanychOVAsync(string login, string password, object userState) {
            if ((this.onBeginZiskatZoznamVydanychOVDelegate == null)) {
                this.onBeginZiskatZoznamVydanychOVDelegate = new BeginOperationDelegate(this.OnBeginZiskatZoznamVydanychOV);
            }
            if ((this.onEndZiskatZoznamVydanychOVDelegate == null)) {
                this.onEndZiskatZoznamVydanychOVDelegate = new EndOperationDelegate(this.OnEndZiskatZoznamVydanychOV);
            }
            if ((this.onZiskatZoznamVydanychOVCompletedDelegate == null)) {
                this.onZiskatZoznamVydanychOVCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnZiskatZoznamVydanychOVCompleted);
            }
            base.InvokeAsync(this.onBeginZiskatZoznamVydanychOVDelegate, new object[] {
                        login,
                        password}, this.onEndZiskatZoznamVydanychOVDelegate, this.onZiskatZoznamVydanychOVCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MalikP.BusinessJournal.Data.Service.JusticeServiceReference.ZiskatPoslednyVydanyOVResponse MalikP.BusinessJournal.Data.Service.JusticeServiceReference.PodanieExportSoap.ZiskatPoslednyVydanyOV(MalikP.BusinessJournal.Data.Service.JusticeServiceReference.ZiskatPoslednyVydanyOVRequest request) {
            return base.Channel.ZiskatPoslednyVydanyOV(request);
        }
        
        public MalikP.BusinessJournal.Data.Service.JusticeServiceReference.ObchodnyVestnik ZiskatPoslednyVydanyOV(string login, string password) {
            MalikP.BusinessJournal.Data.Service.JusticeServiceReference.ZiskatPoslednyVydanyOVRequest inValue = new MalikP.BusinessJournal.Data.Service.JusticeServiceReference.ZiskatPoslednyVydanyOVRequest();
            inValue.Body = new MalikP.BusinessJournal.Data.Service.JusticeServiceReference.ZiskatPoslednyVydanyOVRequestBody();
            inValue.Body.login = login;
            inValue.Body.password = password;
            MalikP.BusinessJournal.Data.Service.JusticeServiceReference.ZiskatPoslednyVydanyOVResponse retVal = ((MalikP.BusinessJournal.Data.Service.JusticeServiceReference.PodanieExportSoap)(this)).ZiskatPoslednyVydanyOV(inValue);
            return retVal.Body.ZiskatPoslednyVydanyOVResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult MalikP.BusinessJournal.Data.Service.JusticeServiceReference.PodanieExportSoap.BeginZiskatPoslednyVydanyOV(MalikP.BusinessJournal.Data.Service.JusticeServiceReference.ZiskatPoslednyVydanyOVRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginZiskatPoslednyVydanyOV(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginZiskatPoslednyVydanyOV(string login, string password, System.AsyncCallback callback, object asyncState) {
            MalikP.BusinessJournal.Data.Service.JusticeServiceReference.ZiskatPoslednyVydanyOVRequest inValue = new MalikP.BusinessJournal.Data.Service.JusticeServiceReference.ZiskatPoslednyVydanyOVRequest();
            inValue.Body = new MalikP.BusinessJournal.Data.Service.JusticeServiceReference.ZiskatPoslednyVydanyOVRequestBody();
            inValue.Body.login = login;
            inValue.Body.password = password;
            return ((MalikP.BusinessJournal.Data.Service.JusticeServiceReference.PodanieExportSoap)(this)).BeginZiskatPoslednyVydanyOV(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MalikP.BusinessJournal.Data.Service.JusticeServiceReference.ZiskatPoslednyVydanyOVResponse MalikP.BusinessJournal.Data.Service.JusticeServiceReference.PodanieExportSoap.EndZiskatPoslednyVydanyOV(System.IAsyncResult result) {
            return base.Channel.EndZiskatPoslednyVydanyOV(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public MalikP.BusinessJournal.Data.Service.JusticeServiceReference.ObchodnyVestnik EndZiskatPoslednyVydanyOV(System.IAsyncResult result) {
            MalikP.BusinessJournal.Data.Service.JusticeServiceReference.ZiskatPoslednyVydanyOVResponse retVal = ((MalikP.BusinessJournal.Data.Service.JusticeServiceReference.PodanieExportSoap)(this)).EndZiskatPoslednyVydanyOV(result);
            return retVal.Body.ZiskatPoslednyVydanyOVResult;
        }
        
        private System.IAsyncResult OnBeginZiskatPoslednyVydanyOV(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string login = ((string)(inValues[0]));
            string password = ((string)(inValues[1]));
            return this.BeginZiskatPoslednyVydanyOV(login, password, callback, asyncState);
        }
        
        private object[] OnEndZiskatPoslednyVydanyOV(System.IAsyncResult result) {
            MalikP.BusinessJournal.Data.Service.JusticeServiceReference.ObchodnyVestnik retVal = this.EndZiskatPoslednyVydanyOV(result);
            return new object[] {
                    retVal};
        }
        
        private void OnZiskatPoslednyVydanyOVCompleted(object state) {
            if ((this.ZiskatPoslednyVydanyOVCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ZiskatPoslednyVydanyOVCompleted(this, new ZiskatPoslednyVydanyOVCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ZiskatPoslednyVydanyOVAsync(string login, string password) {
            this.ZiskatPoslednyVydanyOVAsync(login, password, null);
        }
        
        public void ZiskatPoslednyVydanyOVAsync(string login, string password, object userState) {
            if ((this.onBeginZiskatPoslednyVydanyOVDelegate == null)) {
                this.onBeginZiskatPoslednyVydanyOVDelegate = new BeginOperationDelegate(this.OnBeginZiskatPoslednyVydanyOV);
            }
            if ((this.onEndZiskatPoslednyVydanyOVDelegate == null)) {
                this.onEndZiskatPoslednyVydanyOVDelegate = new EndOperationDelegate(this.OnEndZiskatPoslednyVydanyOV);
            }
            if ((this.onZiskatPoslednyVydanyOVCompletedDelegate == null)) {
                this.onZiskatPoslednyVydanyOVCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnZiskatPoslednyVydanyOVCompleted);
            }
            base.InvokeAsync(this.onBeginZiskatPoslednyVydanyOVDelegate, new object[] {
                        login,
                        password}, this.onEndZiskatPoslednyVydanyOVDelegate, this.onZiskatPoslednyVydanyOVCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MalikP.BusinessJournal.Data.Service.JusticeServiceReference.SkontrolovatZmenyOVResponse MalikP.BusinessJournal.Data.Service.JusticeServiceReference.PodanieExportSoap.SkontrolovatZmenyOV(MalikP.BusinessJournal.Data.Service.JusticeServiceReference.SkontrolovatZmenyOVRequest request) {
            return base.Channel.SkontrolovatZmenyOV(request);
        }
        
        public MalikP.BusinessJournal.Data.Service.JusticeServiceReference.ObchodnyVestnikKapitola[] SkontrolovatZmenyOV(string login, string password, int cislo, int rocnik) {
            MalikP.BusinessJournal.Data.Service.JusticeServiceReference.SkontrolovatZmenyOVRequest inValue = new MalikP.BusinessJournal.Data.Service.JusticeServiceReference.SkontrolovatZmenyOVRequest();
            inValue.Body = new MalikP.BusinessJournal.Data.Service.JusticeServiceReference.SkontrolovatZmenyOVRequestBody();
            inValue.Body.login = login;
            inValue.Body.password = password;
            inValue.Body.cislo = cislo;
            inValue.Body.rocnik = rocnik;
            MalikP.BusinessJournal.Data.Service.JusticeServiceReference.SkontrolovatZmenyOVResponse retVal = ((MalikP.BusinessJournal.Data.Service.JusticeServiceReference.PodanieExportSoap)(this)).SkontrolovatZmenyOV(inValue);
            return retVal.Body.SkontrolovatZmenyOVResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult MalikP.BusinessJournal.Data.Service.JusticeServiceReference.PodanieExportSoap.BeginSkontrolovatZmenyOV(MalikP.BusinessJournal.Data.Service.JusticeServiceReference.SkontrolovatZmenyOVRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginSkontrolovatZmenyOV(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginSkontrolovatZmenyOV(string login, string password, int cislo, int rocnik, System.AsyncCallback callback, object asyncState) {
            MalikP.BusinessJournal.Data.Service.JusticeServiceReference.SkontrolovatZmenyOVRequest inValue = new MalikP.BusinessJournal.Data.Service.JusticeServiceReference.SkontrolovatZmenyOVRequest();
            inValue.Body = new MalikP.BusinessJournal.Data.Service.JusticeServiceReference.SkontrolovatZmenyOVRequestBody();
            inValue.Body.login = login;
            inValue.Body.password = password;
            inValue.Body.cislo = cislo;
            inValue.Body.rocnik = rocnik;
            return ((MalikP.BusinessJournal.Data.Service.JusticeServiceReference.PodanieExportSoap)(this)).BeginSkontrolovatZmenyOV(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MalikP.BusinessJournal.Data.Service.JusticeServiceReference.SkontrolovatZmenyOVResponse MalikP.BusinessJournal.Data.Service.JusticeServiceReference.PodanieExportSoap.EndSkontrolovatZmenyOV(System.IAsyncResult result) {
            return base.Channel.EndSkontrolovatZmenyOV(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public MalikP.BusinessJournal.Data.Service.JusticeServiceReference.ObchodnyVestnikKapitola[] EndSkontrolovatZmenyOV(System.IAsyncResult result) {
            MalikP.BusinessJournal.Data.Service.JusticeServiceReference.SkontrolovatZmenyOVResponse retVal = ((MalikP.BusinessJournal.Data.Service.JusticeServiceReference.PodanieExportSoap)(this)).EndSkontrolovatZmenyOV(result);
            return retVal.Body.SkontrolovatZmenyOVResult;
        }
        
        private System.IAsyncResult OnBeginSkontrolovatZmenyOV(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string login = ((string)(inValues[0]));
            string password = ((string)(inValues[1]));
            int cislo = ((int)(inValues[2]));
            int rocnik = ((int)(inValues[3]));
            return this.BeginSkontrolovatZmenyOV(login, password, cislo, rocnik, callback, asyncState);
        }
        
        private object[] OnEndSkontrolovatZmenyOV(System.IAsyncResult result) {
            MalikP.BusinessJournal.Data.Service.JusticeServiceReference.ObchodnyVestnikKapitola[] retVal = this.EndSkontrolovatZmenyOV(result);
            return new object[] {
                    retVal};
        }
        
        private void OnSkontrolovatZmenyOVCompleted(object state) {
            if ((this.SkontrolovatZmenyOVCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.SkontrolovatZmenyOVCompleted(this, new SkontrolovatZmenyOVCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void SkontrolovatZmenyOVAsync(string login, string password, int cislo, int rocnik) {
            this.SkontrolovatZmenyOVAsync(login, password, cislo, rocnik, null);
        }
        
        public void SkontrolovatZmenyOVAsync(string login, string password, int cislo, int rocnik, object userState) {
            if ((this.onBeginSkontrolovatZmenyOVDelegate == null)) {
                this.onBeginSkontrolovatZmenyOVDelegate = new BeginOperationDelegate(this.OnBeginSkontrolovatZmenyOV);
            }
            if ((this.onEndSkontrolovatZmenyOVDelegate == null)) {
                this.onEndSkontrolovatZmenyOVDelegate = new EndOperationDelegate(this.OnEndSkontrolovatZmenyOV);
            }
            if ((this.onSkontrolovatZmenyOVCompletedDelegate == null)) {
                this.onSkontrolovatZmenyOVCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnSkontrolovatZmenyOVCompleted);
            }
            base.InvokeAsync(this.onBeginSkontrolovatZmenyOVDelegate, new object[] {
                        login,
                        password,
                        cislo,
                        rocnik}, this.onEndSkontrolovatZmenyOVDelegate, this.onSkontrolovatZmenyOVCompletedDelegate, userState);
        }
    }
}
